export const mockArticles = [
    {
      id: 1,
      title: "The Ultimate Guide to JavaScript Array Methods",
      author: "Jane Doe",
      date: "2025-10-26",
      category: "JavaScript",
      tags: ["arrays", "methods", "programming"],
      excerpt: "Learn how to manipulate arrays like a pro with these essential JavaScript methods. From map to reduce, we've got you covered.",
      content: "<p>This is the full article content. You can include HTML tags here for formatting.</p><p>More content...</p>",
      readTime: "5 min",
      views: 1250,
    },
    {
      id: 2,
      title: "Building a Responsive Website with CSS Grid",
      author: "John Smith",
      date: "2025-08-05",
      category: "CSS",
      tags: ["css grid", "responsive design", "web development"],
      excerpt: "Discover the power of CSS Grid for creating flexible and responsive website layouts.",
      content: "<p>This is the full article content about CSS Grid.</p><p>More content...</p>",
      readTime: "8 min",
      views: 875,
    },
    {
      id: 3,
      title: "Introduction to React Hooks",
      author: "Alice Johnson",
      date: "2025-02-12",
      category: "React",
      tags: ["react", "hooks", "frontend"],
      excerpt: "Get started with React Hooks and learn how to manage state and side effects in functional components.",
      content: "<p>React hooks are changing the game. Learn more here.</p><p>More content...</p>",
      readTime: "10 min",
      views: 2100,
    },
    {
      id: 4,
      title: "The Importance of Proper API Documentation",
      author: "Bob Williams",
      date: "2025-09-20",
      category: "APIs",
      tags: ["api", "documentation", "backend"],
      excerpt: "Why good API documentation is crucial for developers and how to create it effectively.",
      content: "<p>Learn how proper API documentation can save you and your users time and frustration.</p><p>More content...</p>",
      readTime: "7 min",
      views: 550,
    },
    {
      id: 5,
      title: "Optimizing Website Performance for Speed",
      author: "Carol Davis",
      date: "2025-11-28",
      category: "Performance",
      tags: ["performance", "optimization", "web development"],
      excerpt: "Tips and techniques to improve your website's loading speed and enhance user experience.",
      content: "<p>Speed matters! Learn how to optimize your website for peak performance.</p><p>More content...</p>",
      readTime: "9 min",
      views: 1800,
    },
  ];